from pathlib import Path
import hashlib, json

root = Path("/workspace/bank")
bodies = Path("/workspace/field/forum0909/bank-bodies")
items = [
  ("2026-09-09-wes-anderson-grok-bot-box-secrets-wiped-overnight", "Grok Bot box secrets wiped overnight (Shopify Client ID/secret)", "https://forum.cursor.com/t/grok-bot-box-secrets-wiped-overnight-shopify-client-id-secret/171029", "Wes_Anderson", "2026-09-08", "171029.txt"),
  ("2026-09-09-ellisfan-grok-bot-conversation-history-rolled-back", "Grok Bot: Conversation history and newly created bots/groups suddenly rolled back and synchronized across all devices", "https://forum.cursor.com/t/grok-bot-conversation-history-and-newly-created-bots-groups-suddenly-rolled-back-and-synchronized-across-all-devices/171008", "ellisfan", "2026-09-08", "171008.txt"),
  ("2026-09-09-oubeichen-same-grok-bot-split-into-different-instances", "Same Grok Bot Split Into Different Instances Across macOS and Android, Causing Duplicate Scheduled Tasks / Usage", "https://forum.cursor.com/t/same-grok-bot-split-into-different-instances-across-macos-and-android-causing-duplicate-scheduled-tasks-usage/170989", "oubeichen", "2026-09-08", "170989.txt"),
]
idx = {}
ip = root / "index.jsonl"
if ip.exists():
  for line in ip.read_text().splitlines():
    if line.strip():
      o = json.loads(line)
      idx[o["id"]] = o
seen_src = {o.get("source"): o["id"] for o in idx.values() if o.get("source")}
for iid, title, source, author, published, bodyfile in items:
  if source in seen_src:
    print("DUP", source, "->", seen_src[source])
    continue
  body = (bodies / bodyfile).read_text()
  fm = (
    f"---\n"
    f"id: {iid}\n"
    f"kind: article\n"
    f"title: {json.dumps(title)}\n"
    f"source: {json.dumps(source)}\n"
    f"author: {author}\n"
    f"published: {published}\n"
    f"captured: 2026-09-09\n"
    f"via: grok-bot/Field\n"
    f"lane: ai\n"
    f"status: raw\n"
    f"private: false\n"
    f"---\n\n"
  )
  out = root / "raw" / "ai" / f"{iid}.md"
  out.write_text(fm + body)
  o = {
    "id": iid, "kind": "article", "title": title, "source": source,
    "author": author, "published": published, "captured": "2026-09-09",
    "via": "grok-bot/Field", "lane": "ai", "status": "raw", "private": False,
    "raw": str(out.relative_to(root)),
    "body_sha": hashlib.sha1(body.encode()).hexdigest()[:12],
    "card": "", "used_by": [],
  }
  idx[iid] = o
  print("WROTE", out)

rows = sorted(idx.values(), key=lambda o: o["id"])
ip.write_text("".join(json.dumps(o, ensure_ascii=False) + "\n" for o in rows))
by_lane = {}
for o in rows:
  by_lane.setdefault(o["lane"], []).append(o)
md = ["# INDEX", "", f"Generated by scripts/bank.py --index. {len(rows)} items. Do not edit.", ""]
for lane in sorted(by_lane):
  md.append(f"## {lane} ({len(by_lane[lane])})")
  md.append("")
  md.append("| id | kind | title | status | card | source |")
  md.append("|---|---|---|---|---|---|")
  for o in by_lane[lane]:
    priv = " 🔒" if o.get("private") else ""
    card = "yes" if o.get("card") else ""
    md.append(
      f"| `{o['id']}`{priv} | {o['kind']} | {o['title'][:70]} | {o['status']} | {card} | {o['source'][:60]} |"
    )
  md.append("")
(root / "INDEX.md").write_text("\n".join(md))
print("INDEX rebuilt", len(rows))
